services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: rawy
      POSTGRES_PASSWORD: rawy
      POSTGRES_DB: rawy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
